from app import AIAgentLibraryManagementSystem

def add_sample_books():
    ai_agent_lms = AIAgentLibraryManagementSystem()

    # Add sample books to the database
    ai_agent_lms.add_book("1984", 5)
    ai_agent_lms.add_book("To Kill a Mockingbird", 3)
    ai_agent_lms.add_book("The Great Gatsby", 2)
    ai_agent_lms.add_book("Moby Dick", 4)
    ai_agent_lms.add_book("Pride and Prejudice", 6)
    ai_agent_lms.add_book("The Catcher in the Rye", 3)
    ai_agent_lms.add_book("The Hobbit", 7)
    ai_agent_lms.add_book("War and Peace", 4)
    ai_agent_lms.add_book("The Odyssey", 6)
    ai_agent_lms.add_book("Brave New World", 5)
    ai_agent_lms.add_book("Crime and Punishment", 2)
    ai_agent_lms.add_book("The Brothers Karamazov", 3)
    ai_agent_lms.add_book("Wuthering Heights", 4)
    ai_agent_lms.add_book("Jane Eyre", 5)
    ai_agent_lms.add_book("The Picture of Dorian Gray", 4)
    ai_agent_lms.add_book("Fahrenheit 451", 6)
    ai_agent_lms.add_book("Catch-22", 3)
    ai_agent_lms.add_book("Frankenstein", 5)
    ai_agent_lms.add_book("Dracula", 3)
    ai_agent_lms.add_book("The Lord of the Rings", 7)
    ai_agent_lms.add_book("Animal Farm", 6)
    ai_agent_lms.add_book("The Grapes of Wrath", 4)
    ai_agent_lms.add_book("The Scarlet Letter", 5)
    ai_agent_lms.add_book("The Shining", 3)
    ai_agent_lms.add_book("Harry Potter and the Sorcerer's Stone", 8)
    ai_agent_lms.add_book("The Hunger Games", 5)
    ai_agent_lms.add_book("The Maze Runner", 4)
    ai_agent_lms.add_book("The Fault in Our Stars", 6)
    ai_agent_lms.add_book("A Game of Thrones", 7)
    ai_agent_lms.add_book("Ender's Game", 4)
    ai_agent_lms.add_book("The Alchemist", 6)
    ai_agent_lms.add_book("The Chronicles of Narnia", 5)
    ai_agent_lms.add_book("The Secret Garden", 3)
    ai_agent_lms.add_book("The Bell Jar", 4)
    ai_agent_lms.add_book("Gone with the Wind", 5)
    ai_agent_lms.add_book("The Kite Runner", 4)
    ai_agent_lms.add_book("The Great Alone", 3)
    ai_agent_lms.add_book("The Outsiders", 6)
    ai_agent_lms.add_book("Little Women", 5)

if __name__ == "__main__":
    add_sample_books()